import type {
  ChampionMasteryDTO,
  PlayerDTO,
  ConfigDTO,
  PercentilesDTO,
  LeagueListDTO,
  LeagueEntryDTO,
  CurrentGameInfoDTO,
  FeaturedGamesDTO,
  LolStatusPlatformDataDTO,
  SummonerV4DTO,
  SummonerLeagueDto,
  MatchV5DTOs,
  MatchV5TimelineDTOs,
  ChampionRotationV3DTO,
  ApiResponseDTO,
} from 'twisted/dist/models-dto';
import type {
  ChampionsDataDragon,
  ChampionsDataDragonDetailsSolo,
  RealmDTO,
  QueuesDataDragonDTO,
  MapsDataDragonDTO,
  GameModesDataDragonDTO,
} from 'twisted/dist/models-dto/data-dragon/index';
import type {
  RunesReforgedDTO,
  RunesReforgedSlotsDTO,
} from 'twisted/dist/models-dto/data-dragon/runes-reforged.dto';

export type {
  ChampionMasteryDTO,
  PlayerDTO,
  ConfigDTO,
  PercentilesDTO,
  LeagueListDTO,
  LeagueEntryDTO,
  CurrentGameInfoDTO,
  FeaturedGamesDTO,
  LolStatusPlatformDataDTO,
  SummonerV4DTO,
  SummonerLeagueDto,
  MatchV5DTOs,
  MatchV5TimelineDTOs,
  ChampionRotationV3DTO,
  ChampionsDataDragon,
  ChampionsDataDragonDetailsSolo,
  ApiResponseDTO,
  RealmDTO,
  QueuesDataDragonDTO,
  MapsDataDragonDTO,
  GameModesDataDragonDTO,
  RunesReforgedDTO,
  RunesReforgedSlotsDTO,
};
